name: QA

on:
  pull_request_target:
    types: [opened, reopened]

jobs:
  appstore:
    runs-on: macos-latest
    strategy:
      matrix:
        tuist: [ '3.16.0' ]
        ruby: [ '2.7' ]

    steps:
      - uses: actions/checkout@v2
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: brew install fastlane
      - run: bundle update fastlane
      - run: bundle exec fastlane set_version version:1.0.0
      - name: Install Tuist
        run: |
          curl -L -o ./tuist.zip https://github.com/tuist/tuist/releases/download/${{ matrix.tuist }}/tuist.zip
          unzip ./tuist.zip -d .tuist-bin
      - name: tuist generate
        run: |
          .tuist-bin/tuist fetch
          .tuist-bin/tuist generate
      - run: bundle exec fastlane QA_CD
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSPHRASE }}
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          APP_STORE_CONNECT_API_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT }}
